"use client";

import { Sparkles, Wrench } from "lucide-react";
import type { Locale } from "@/hooks/use-locale";
import type { AnalysisEngine } from "@/lib/report-result-utils";

type ReportAnalysisEngineBadgeProps = {
  engine: AnalysisEngine | null;
  locale: Locale;
  loading?: boolean;
};

export function ReportAnalysisEngineBadge({
  engine,
  locale,
  loading = false,
}: ReportAnalysisEngineBadgeProps) {
  if (loading) {
    return (
      <span className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-medium text-slate-600">
        {locale === "id" ? "Mesin: memuat…" : "Engine: loading…"}
      </span>
    );
  }

  if (!engine) return null;

  const isAi = engine === "ai";
  const label = isAi
    ? locale === "id"
      ? "Mesin: AI"
      : "Engine: AI"
    : locale === "id"
      ? "Mesin: Aturan"
      : "Engine: Rule-based";
  const hint = isAi
    ? locale === "id"
      ? "Ringkasan dibuat oleh model AI (Ollama)"
      : "Summary generated by AI model (Ollama)"
    : locale === "id"
      ? "Ringkasan dari ekstraksi aturan (tanpa model AI)"
      : "Summary from rule-based extraction (no AI model)";

  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium ${
        isAi
          ? "border-indigo-200 bg-indigo-50 text-indigo-800"
          : "border-amber-200 bg-amber-50 text-amber-900"
      }`}
      title={hint}
    >
      {isAi ? (
        <Sparkles className="h-3 w-3 shrink-0" aria-hidden />
      ) : (
        <Wrench className="h-3 w-3 shrink-0" aria-hidden />
      )}
      {label}
    </span>
  );
}
